### ISSUE TITLE
Diverse beam search 

### ISSUE THREAD

**Issue by hljjjmssyh** [huggingface/optimum-intel#114]
Hi！I trained a T5 model, and accelerated it with openvino.
But when I use diverse beam search algorithm to generate results, the results seem wrong. 
The result is inconsistent with the original huggingface model.
<img width="1106" alt="image" src="https://user-images.githubusercontent.com/24326757/203493644-3ff4ee77-77c4-4305-b631-2b3b312a0728.png">

**Comment by echarlaix** [comment]
Hi @hljjjmssyh,

Can you try with `openvino` `2022.3.0.dev20221125` ?

**Comment by echarlaix** [comment]
Thanks a lot for reporting this issue @hljjjmssyh ! It has been fixed with `openvino` `v2022.3.0`. Don't hesitate to open a new issue in case you encounter any other problem !
