### ISSUE TITLE
Quantization of AutoModelForCausalLM error

### ISSUE THREAD

**Issue by simoroma** [huggingface/optimum-intel#172]
When I try to quantize such a model I get the following error: `KeyError: 'text-generation'` in `FeaturesManager._SUPPORTED_MODEL_TYPE[model_type][self.feature]`

I thought that AutoModelForCausalLM was supported?

**Comment by echarlaix** [comment]
Hi @simoroma, 

Causal language models are not yet supported for quantization using OpenVINO NNCF but we are currently working on its integration.
