### ISSUE TITLE
Problem about about text-image

### ISSUE THREAD

**Issue by Christianqling2** [huggingface/optimum-intel#178]
I test the code on the examples of text-image and I found that load_quantized_model will use the original model to replace the quantized model.  Can you tell me the version of the packages for this example? Or it is just a fake load_quantized_model?

**Comment by echarlaix** [comment]
Hi @Christianqling2, 

We recently introduced the [`INCStableDiffusionPipeline`](https://github.com/huggingface/optimum-intel/blob/65d6bc46cd2c483117ee59c345835899e2fb1456/optimum/intel/neural_compressor/modeling_diffusion.py#L26) class to enable the loading of INC quantized Stable Diffusion models, the [examples](https://github.com/huggingface/optimum-intel/blob/65d6bc46cd2c483117ee59c345835899e2fb1456/examples/neural_compressor/text-to-image/run_diffusion_post_training.py#L35) were also updated. To try it out, you can install `optimum-intel` from [source](https://huggingface.co/docs/optimum/main/en/intel/installation). Let us know if you encounter any issues!

**Comment by JiaojiaoYe1994** [comment]
Hi, greate implementations! By the way, I have a question regarding the static PTQ, does it support other granuality except for INT8.
