### ISSUE TITLE
Neural Compressor - quantization supported for GPUs

### ISSUE THREAD

**Issue by jmdu99** [huggingface/optimum-intel#203]
> Note that quantization is currently only supported for CPUs (only CPU backends are available), so we will not be utilizing GPUs / CUDA in this example.

I just wanted to ask when the quantization for GPUs will be supported (approximate date). We are working on optimizing Seq2Seq models for summarization task and we believe that this can be quite useful.

**Comment by echarlaix** [comment]
Hi @jmdu99 ,

Only the FakeQuantize modules are supported on cuda, while the quantized operations are currently implemented on cpu only for PyTorch. This means that you can train your model while applying quantization on cuda but that inference needs to be performed on cpu.

Just make sure that neural-compressor>v2.0, you can install it from source :
pip install git+https://github.com/intel/neural-compressor
