### ISSUE TITLE
Openvino interface

### ISSUE THREAD

**Issue by Zjq9409** [huggingface/optimum-intel#219]
Is there an interface similar to downloading files in openvino?
```
from huggingface_hub import hf_hub_download
hf_hub_download(repo_id="lysandre/arxiv-nlp", filename="config.json")
```

**Comment by echarlaix** [comment]
Hi @Zjq9409,

Yes  `hf_hub_download` can be used to download files if not already present in the local cache.
```python 
from huggingface_hub import hf_hub_download

file_path = hf_hub_download(repo_id="echarlaix/t5-small-openvino", filename="openvino_decoder_model.xml")
```
You can also specify the cache directory in case you don't want to use the default one using the `cache_dir` parameter.
