### ISSUE TITLE
Is it possible to do pruning, distillation and QAT in one single step on GPU?

### ISSUE THREAD

**Issue by rohanshingade** [huggingface/optimum-intel#29]
The documentation says, quantization is not supported on cuda. Is there any work around to apply pruning, distillation and QAT in one step?

**Comment by echarlaix** [comment]
Hi @rohanshingade,

Only the FakeQuantize modules are supported on cuda, while the quantized operations are implemented on cpu only. This means that you can train your model while applying quantization (combined with the compression techniques you mentionned) using cuda but that inference needs to be performed on cpu. 

Just make sure that `neural-compressor>v2.0`, you can install it from source :
`pip install git+https://github.com/intel/neural-compressor`
