### ISSUE TITLE
Degradation in audio and image classification samples with new transformers package

### ISSUE THREAD

**Issue by ljaljushkin** [huggingface/optimum-intel#345]
Audio and image classification samples fail with error `AttributeError: <> object has no attribute 'no_sync'`

For example, [Command line](https://github.com/huggingface/optimum-intel/tree/main/examples/openvino/audio-classification#fine-tuning-wav2vec2-on-keyword-spotting-with-qat
) for finetuning of wave2vec with QAT fails with 

`AttributeError: 'Wav2Vec2ForSequenceClassification' object has no attribute 'no_sync'`

It's reproduced with latest version of transformers: 4.30.0 
There's no such issue with 4.22.0 version

**Comment by ljaljushkin** [comment]
@helena-intel @AlexKoff88 @echarlaix @vuiseng9 @yujiepan-work

**Comment by AlexKoff88** [comment]
@ljaljushkin, it seems like this is not an Optimum-related problem but rather a Transformer problem. Some relevant issues: https://discuss.huggingface.co/t/distributeddataparallel-object-has-no-attribute-no-sync/5469
I think it should be worked around in the sample.

**Comment by helena-intel** [comment]
@ljaljushkin thanks for reporting this. The examples are definitely expected to work out of the box with the version of transformers we install as dependency. Could you try running with torchrun like you changed for some other runs in #315 ?

**Comment by ljaljushkin** [comment]
> @ljaljushkin thanks for reporting this. The examples are definitely expected to work out of the box with the version of transformers we install as dependency. Could you try running with torchrun like you changed for some other runs in #315 ?

Yes, I had verified that. The issue is reproduced for mentioned samples only.

**Comment by ljaljushkin** [comment]
@helena-intel this is not reproduced on the main branch now. But audio sample still doesn't work #423
