### ISSUE TITLE
Please consider to remove OV model cache enabling for model compiling

### ISSUE THREAD

**Issue by FionaZZ92** [huggingface/optimum-intel#347]
Currently, OV model cache is not actual bring benefit on CPU, and GPU also generates cache file larger than original weights. I recommend to remove model cache enabling at this moment in case bring negative feedback from users.

When we call "OVModelForCausalLM.from_pretrained" the model compiled by OV to generate IR, below source code required to compiling with cache. Please consider to modify it disable it when using CPU, enable it on GPU.

[https://github.com/huggingface/optimum-intel/blob/main/optimum/intel/openvino/modeling_base.py#L318](https://github.com/huggingface/optimum-intel/blob/main/optimum/intel/openvino/modeling_base.py#L318)

![image](https://github.com/huggingface/optimum-intel/assets/44352144/8c07b735-5bc1-44c9-a513-cb3232a3a5c5)

Without model cache, it just require 40s to compile.

**Comment by helena-intel** [comment]
Hi Fiona, model caching is supported on CPU, and can help quite a bit with some large models. If loading from cache takes longer than without cache for certain models, that looks like an issue with OpenVINO. Could you raise that there?

I do agree with you that we should have an option to disable model caching, and to override the CACHE_DIR directory.  cc @echarlaix

**Comment by FionaZZ92** [comment]
Sorry Helena, my mistake, I used optimum-cli generated model to compare the loading time. 
The optimum-intel generated llama 7b every time requires 260s for first compiling, by using cache, next time decrease to 47.5s. The inference perf looks also affected by compiling costs.
<img width="1886" alt="MicrosoftTeams-image (25)" src="https://github.com/huggingface/optimum-intel/assets/44352144/210ca093-074c-4c4b-8308-62d136158d96">

We also tried to load model generated by optimum-cli, it only take 45.8s for 1st time compiling. I think you may close this ticket, cache helps. But we should figure out the huge costs for 1st time compiling.

**Comment by echarlaix** [comment]
Sure @helena-intel, just opened https://github.com/huggingface/optimum-intel/issues/352
