### ISSUE TITLE
Add an option to disable OpenVINO model caching

### ISSUE THREAD

**Issue by echarlaix** [huggingface/optimum-intel#352]
Add an option to disable model caching and to override the CACHE_DIR directory when loading an `OVModel` 

cc @helena-intel

**Comment by peterchen-intel** [comment]
https://github.com/huggingface/optimum-intel/blob/c56d3b42/optimum/intel/openvino/modeling_base.py#L335 Should not hard code here? At least should allow ov_config to overwrite it to empty(disabled) instead of overwrite the setting inside ov_config.

**Comment by helena-intel** [comment]
@peterchen-intel  that is the goal of this issue indeed (also in other modeling files). It should still be enabled by default with a standard directory, because it is a good default and many users are not aware of the option of model caching.

**Comment by peterchen-intel** [comment]
@helena-intel How about [Allow user to set the CACHE_DIR #362 ](https://github.com/huggingface/optimum-intel/pull/362) ?
