### ISSUE TITLE
not suppoer IntermediateLayersKnowledgeDistillationLossConfig and SelfKnowledgeDistillationLossConfig?

### ISSUE THREAD

**Issue by lewis-v** [huggingface/optimum-intel#372]
The error occurred in compute_distillation_loss method of train.py file

```
    def compute_distillation_loss(self, student_outputs, teacher_outputs):
        """
        How the distillation loss is computed given the student and teacher outputs.
        """
        distillation_loss = None
        temperature = self.distillation_callback.criterion.temperature // error 1
        for student_output, teacher_output in zip(student_outputs, teacher_outputs):
            student_output = student_output / temperature
            teacher_output = teacher_output / temperature
            loss = self.distillation_callback.criterion.teacher_student_loss_cal(student_output, teacher_output) // error 2
            distillation_loss = loss if distillation_loss is None else distillation_loss + loss
        distillation_loss *= temperature**2
        return distillation_loss

```
- 'PyTorchIntermediateLayersKnowledgeDistillationLoss' object has no attribute 'temperature'
- 'PyTorchIntermediateLayersKnowledgeDistillationLoss' object has not teacher_student_loss_cal
- 'PyTorchSelfKnowledgeDistillationLoss' object has not teacher_student_loss_cal

What is the reason for this? Is it not supported by itself or am I using it in a wrong way

python：3.8.8
neural-compressor：2.2
optimum-intel：1.9.1.dev0

**Comment by echarlaix** [comment]
Hi @lewis-v, 

Apologies for the late reply, intra-layer distillation is currently not supported by the `INCTrainer`. An error should be raised on our side when an unsupported distillation config is provided, thanks for letting us know !
