### ISSUE TITLE
TrOcr model to openvino IR model

### ISSUE THREAD

**Issue by khalidtariq** [huggingface/optimum-intel#379]
### Feature request

hi everyone, i have a TrOcr model and i would like to convert it to openvino IR model. I tried with the optimum, I think, does not support the Trocr model. Has anyone done this before and can help me out, I would really appreciate it

### Motivation

need help 

### Your contribution

need help

**Comment by regisss** [comment]
Transferring this issue to Optimum Intel as that's where exports to OpenVINO are managed.

**Comment by echarlaix** [comment]
`OVModelForVision2Seq` support for TrOCR models is now available thanks to https://github.com/huggingface/optimum-intel/pull/634
