### ISSUE TITLE
INCStableDiffusionPipeline toolkit

### ISSUE THREAD

**Issue by JiaojiaoYe1994** [huggingface/optimum-intel#385]
Hi, guys, thank for the pretty cool project. One question regarding the use of Neural Compressor as the following. I guess it is the version problem and tries to reinstall Neural Compressor by `python -m pip install optimum[neural-compressor]` . 

**Environment:**
- optimum                       1.8.7.dev0
- neural-compressor             2.2.1

**To Reproduce:**

`from optimum.intel import INCQuantizer, INCStableDiffusionPipeline` 

**Return:**

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /usr/local/lib/python3.8/dist-packages/neural_compressor/utils/utility.py:103 in __getattr__     │
│                                                                                                  │
│    100 │   def __getattr__(self, name):                                                          │
│    101 │   │   """Get the attributes of the module by name."""                                   │
│    102 │   │   try:                                                                              │
│ ❱  103 │   │   │   self.module = importlib.import_module(self.module_name)                       │
│    104 │   │   │   mod = getattr(self.module, name)                                              │
│    105 │   │   except:                                                                           │
│    106 │   │   │   spec = importlib.util.find_spec(str(self.module_name + '.' + name))           │
│                                                                                                  │
│ /usr/lib/python3.8/importlib/__init__.py:127 in import_module                                    │
│                                                                                                  │
│   124 │   │   │   if character != '.':                                                           │
│   125 │   │   │   │   break                                                                      │
│   126 │   │   │   level += 1                                                                     │
│ ❱ 127 │   return _bootstrap._gcd_import(name[level:], package, level)                            │
│   128                                                                                            │
│   129                                                                                            │
│   130 _RELOADING = {}                                                                            │
│ in _gcd_import:1014                                                                              │
│ in _find_and_load:991                                                                            │
│ in _find_and_load_unlocked:975                                                                   │
│ in _load_unlocked:671                                                                            │
│ in exec_module:843                                                                               │
│ in _call_with_frames_removed:219                                                                 │
│                                                                                                  │
│ /usr/local/lib/python3.8/dist-packages/cv2/__init__.py:181 in <module>                           │
│                                                                                                  │
│   178 │   if DEBUG: print('OpenCV loader: DONE')                                                 │
│   179                                                                                            │
│   180                                                                                            │
│ ❱ 181 bootstrap()                                                                                │
│   182                                                                                            │
│                                                                                                  │
│ /usr/local/lib/python3.8/dist-packages/cv2/__init__.py:175 in bootstrap                          │
│                                                                                                  │
│   172 │   if DEBUG: print('OpenCV loader: binary extension... OK')                               │
│   173 │                                                                                          │
│   174 │   for submodule in __collect_extra_submodules(DEBUG):                                    │
│ ❱ 175 │   │   if __load_extra_py_code_for_module("cv2", submodule, DEBUG):                       │
│   176 │   │   │   if DEBUG: print("Extra Python code for", submodule, "is loaded")               │
│   177 │                                                                                          │
│   178 │   if DEBUG: print('OpenCV loader: DONE')                                                 │
│                                                                                                  │
│ /usr/local/lib/python3.8/dist-packages/cv2/__init__.py:28 in __load_extra_py_code_for_module     │
│                                                                                                  │
│    25 │   export_module_name = "{}.{}".format(base, name)                                        │
│    26 │   native_module = sys.modules.pop(module_name, None)                                     │
│    27 │   try:                                                                                   │
│ ❱  28 │   │   py_module = importlib.import_module(module_name)                                   │
│    29 │   except ImportError as err:                                                             │
│    30 │   │   if enable_debug_print:                                                             │
│    31 │   │   │   print("Can't load Python code for module:", module_name,                       │
│                                                                                                  │
│ /usr/lib/python3.8/importlib/__init__.py:127 in import_module                                    │
│                                                                                                  │
│   124 │   │   │   if character != '.':                                                           │
│   125 │   │   │   │   break                                                                      │
│   126 │   │   │   level += 1                                                                     │
│ ❱ 127 │   return _bootstrap._gcd_import(name[level:], package, level)                            │
│   128                                                                                            │
│   129                                                                                            │
│   130 _RELOADING = {}                                                                            │
│ in _gcd_import:1014                                                                              │
│ in _find_and_load:991                                                                            │
│ in _find_and_load_unlocked:975                                                                   │
│ in _load_unlocked:671                                                                            │
│ in exec_module:843                                                                               │
│ in _call_with_frames_removed:219                                                                 │
│                                                                                                  │
│ /usr/local/lib/python3.8/dist-packages/cv2/mat_wrapper/__init__.py:33 in <module>                │
│                                                                                                  │
│   30                                                                                             │
│   31 Mat.__module__ = cv.__name__                                                                │
│   32 cv.Mat = Mat                                                                                │
│ ❱ 33 cv._registerMatType(Mat)                                                                    │
│   34                                                                                             │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: partially initialized module 'cv2' has no attribute '_registerMatType' (most likely due to a 
circular import)

During handling of the above exception, another exception occurred:

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /usr/local/lib/python3.8/dist-packages/transformers/utils/import_utils.py:1146 in _get_module    │
│                                                                                                  │
│   1143 │                                                                                         │
│   1144 │   def _get_module(self, module_name: str):                                              │
│   1145 │   │   try:                                                                              │
│ ❱ 1146 │   │   │   return importlib.import_module("." + module_name, self.__name__)              │
│   1147 │   │   except Exception as e:                                                            │
│   1148 │   │   │   raise RuntimeError(                                                           │
│   1149 │   │   │   │   f"Failed to import {self.__name__}.{module_name} because of the followin  │
│                                                                                                  │
│ /usr/lib/python3.8/importlib/__init__.py:127 in import_module                                    │
│                                                                                                  │
│   124 │   │   │   if character != '.':                                                           │
│   125 │   │   │   │   break                                                                      │
│   126 │   │   │   level += 1                                                                     │
│ ❱ 127 │   return _bootstrap._gcd_import(name[level:], package, level)                            │
│   128                                                                                            │
│   129                                                                                            │
│   130 _RELOADING = {}                                                                            │
│ in _gcd_import:1014                                                                              │
│ in _find_and_load:991                                                                            │
│ in _find_and_load_unlocked:975                                                                   │
│ in _load_unlocked:671                                                                            │
│ in exec_module:843                                                                               │
│ in _call_with_frames_removed:219                                                                 │
│                                                                                                  │
│ /usr/local/lib/python3.8/dist-packages/optimum/intel/neural_compressor/__init__.py:17 in         │
│ <module>                                                                                         │
│                                                                                                  │
│   14                                                                                             │
│   15 from ..utils.import_utils import is_diffusers_available                                     │
│   16 from .configuration import INCConfig                                                        │
│ ❱ 17 from .quantization import (                                                                 │
│   18 │   INCModel,                                                                               │
│   19 │   INCModelForCausalLM,                                                                    │
│   20 │   INCModelForMaskedLM,                                                                    │
│                                                                                                  │
│ /usr/local/lib/python3.8/dist-packages/optimum/intel/neural_compressor/quantization.py:28 in     │
│ <module>                                                                                         │
│                                                                                                  │
│    25 import torch                                                                               │
│    26 from datasets import Dataset, load_dataset                                                 │
│    27 from huggingface_hub import HfApi, hf_hub_download                                         │
│ ❱  28 from neural_compressor.adaptor.pytorch import PyTorch_FXAdaptor, _cfg_to_qconfig, _propa   │
│    29 from neural_compressor.config import PostTrainingQuantConfig                               │
│    30 from neural_compressor.experimental.export import torch_to_int8_onnx                       │
│    31 from neural_compressor.model.torch_model import IPEXModel, PyTorchModel                    │
│                                                                                                  │
│ /usr/local/lib/python3.8/dist-packages/neural_compressor/__init__.py:24 in <module>              │
│                                                                                                  │
│   21 from .config import DistillationConfig, PostTrainingQuantConfig, \                          │
│   22 │   │   │   │   │   WeightPruningConfig, QuantizationAwareTrainingConfig, \                 │
│   23 │   │   │   │   │   MixedPrecisionConfig                                                    │
│ ❱ 24 from .contrib import *                                                                      │
│   25 from .model import *                                                                        │
│   26 from .metric import *                                                                       │
│   27 from .utils import options                                                                  │
│                                                                                                  │
│ /usr/local/lib/python3.8/dist-packages/neural_compressor/contrib/__init__.py:19 in <module>      │
│                                                                                                  │
│   16 # limitations under the License.                                                            │
│   17                                                                                             │
│   18 """Built-in strategy for multiple framework backends."""                                    │
│ ❱ 19 from .strategy import *                                                                     │
│   20                                                                                             │
│                                                                                                  │
│ /usr/local/lib/python3.8/dist-packages/neural_compressor/contrib/strategy/__init__.py:26 in      │
│ <module>                                                                                         │
│                                                                                                  │
│   23                                                                                             │
│   24 for f in modules:                                                                           │
│   25 │   if isfile(f) and not f.startswith('__') and not f.endswith('__init__.py'):              │
│ ❱ 26 │   │   __import__(basename(f)[:-3], globals(), locals(), level=1)                          │
│   27                                                                                             │
│   28                                                                                             │
│                                                                                                  │
│ /usr/local/lib/python3.8/dist-packages/neural_compressor/contrib/strategy/tpe.py:26 in <module>  │
│                                                                                                  │
│    23 import numpy as np                                                                         │
│    24 from neural_compressor.utils import logger                                                 │
│    25 from neural_compressor.utils.utility import LazyImport                                     │
│ ❱  26 from neural_compressor.strategy.strategy import strategy_registry, TuneStrategy            │
│    27 from collections import OrderedDict                                                        │
│    28 from neural_compressor.strategy.utils.tuning_sampler import OpWiseTuningSampler            │
│    29 from neural_compressor.strategy.utils.tuning_structs import OpTuningConfig                 │
│                                                                                                  │
│ /usr/local/lib/python3.8/dist-packages/neural_compressor/strategy/__init__.py:20 in <module>     │
│                                                                                                  │
│   17                                                                                             │
│   18 """Intel Neural Compressor Strategy."""                                                     │
│   19                                                                                             │
│ ❱ 20 from .strategy import STRATEGIES                                                            │
│   21 from os.path import dirname, basename, isfile, join                                         │
│   22 import glob                                                                                 │
│   23                                                                                             │
│                                                                                                  │
│ /usr/local/lib/python3.8/dist-packages/neural_compressor/strategy/strategy.py:35 in <module>     │
│                                                                                                  │
│     32 import numpy as np                                                                        │
│     33 import yaml                                                                               │
│     34                                                                                           │
│ ❱   35 from neural_compressor.adaptor.tensorflow import TensorFlowAdaptor                        │
│     36 from neural_compressor.config import MixedPrecisionConfig                                 │
│     37 from .utils.constant import FALLBACK_RECIPES_SET                                          │
│     38 from .utils.tuning_space import TuningSpace                                               │
│                                                                                                  │
│ /usr/local/lib/python3.8/dist-packages/neural_compressor/adaptor/__init__.py:26 in <module>      │
│                                                                                                  │
│   23                                                                                             │
│   24 for f in modules:                                                                           │
│   25 │   if isfile(f) and not f.startswith('__') and not f.endswith('__init__.py'):              │
│ ❱ 26 │   │   __import__(basename(f)[:-3], globals(), locals(), level=1)                          │
│   27                                                                                             │
│   28 __all__ = ["FRAMEWORKS"]                                                                    │
│   29                                                                                             │
│                                                                                                  │
│ /usr/local/lib/python3.8/dist-packages/neural_compressor/adaptor/pytorch.py:33 in <module>       │
│                                                                                                  │
│     30 from ..utils.utility import Statistics                                                    │
│     31 from ..utils import logger                                                                │
│     32 from .query import QueryBackendCapability                                                 │
│ ❱   33 from ..data.dataloaders.base_dataloader import BaseDataLoader                             │
│     34 torch = LazyImport("torch")                                                               │
│     35 json = LazyImport("json")                                                                 │
│     36 hvd = LazyImport("horovod.torch")                                                         │
│                                                                                                  │
│ /usr/local/lib/python3.8/dist-packages/neural_compressor/data/__init__.py:22 in <module>         │
│                                                                                                  │
│   19                                                                                             │
│   20                                                                                             │
│   21 import neural_compressor.data.datasets                                                      │
│ ❱ 22 import neural_compressor.data.transforms                                                    │
│   23 from .datasets import Datasets, Dataset, IterableDataset, dataset_registry, TensorflowIm    │
│   24 from .dataloaders import DATALOADERS, DataLoader                                            │
│   25 from .dataloaders.dataloader import check_dataloader                                        │
│                                                                                                  │
│ /usr/local/lib/python3.8/dist-packages/neural_compressor/data/transforms/__init__.py:20 in       │
│ <module>                                                                                         │
│                                                                                                  │
│   17 # ==============================================================================            │
│   18 """Neural Compressor Built-in transforms for multiple framework backends."""                │
│   19                                                                                             │
│ ❱ 20 from .transform import TRANSFORMS, BaseTransform, ComposeTransform, transform_registry,     │
│   21 ResizeTFTransform, TensorflowResizeWithRatio, RescaleTFTransform, NormalizeTFTransform      │
│   22 from .transform import TFSquadV1PostTransform, TFSquadV1ModelZooPostTransform               │
│   23 from .coco_transform import ParseDecodeCocoTransform                                        │
│                                                                                                  │
│ /usr/local/lib/python3.8/dist-packages/neural_compressor/data/transforms/transform.py:478 in     │
│ <module>                                                                                         │
│                                                                                                  │
│    475 │   │   return (image, label)                                                             │
│    476                                                                                           │
│    477 interpolation_map = {                                                                     │
│ ❱  478 │   'nearest': cv2.INTER_NEAREST,                                                         │
│    479 │   'bilinear': cv2.INTER_LINEAR,                                                         │
│    480 │   'bicubic': cv2.INTER_CUBIC,                                                           │
│    481 }                                                                                         │
│                                                                                                  │
│ /usr/local/lib/python3.8/dist-packages/neural_compressor/utils/utility.py:106 in __getattr__     │
│                                                                                                  │
│    103 │   │   │   self.module = importlib.import_module(self.module_name)                       │
│    104 │   │   │   mod = getattr(self.module, name)                                              │
│    105 │   │   except:                                                                           │
│ ❱  106 │   │   │   spec = importlib.util.find_spec(str(self.module_name + '.' + name))           │
│    107 │   │   │   mod = importlib.util.module_from_spec(spec)                                   │
│    108 │   │   │   spec.loader.exec_module(mod)                                                  │
│    109 │   │   return mod                                                                        │
│                                                                                                  │
│ /usr/lib/python3.8/importlib/util.py:94 in find_spec                                             │
│                                                                                                  │
│    91 │   if fullname not in sys.modules:                                                        │
│    92 │   │   parent_name = fullname.rpartition('.')[0]                                          │
│    93 │   │   if parent_name:                                                                    │
│ ❱  94 │   │   │   parent = __import__(parent_name, fromlist=['__path__'])                        │
│    95 │   │   │   try:                                                                           │
│    96 │   │   │   │   parent_path = parent.__path__                                              │
│    97 │   │   │   except AttributeError as e:                                                    │
│                                                                                                  │
│ /usr/local/lib/python3.8/dist-packages/cv2/__init__.py:181 in <module>                           │
│                                                                                                  │
│   178 │   if DEBUG: print('OpenCV loader: DONE')                                                 │
│   179                                                                                            │
│   180                                                                                            │
│ ❱ 181 bootstrap()                                                                                │
│   182                                                                                            │
│                                                                                                  │
│ /usr/local/lib/python3.8/dist-packages/cv2/__init__.py:175 in bootstrap                          │
│                                                                                                  │
│   172 │   if DEBUG: print('OpenCV loader: binary extension... OK')                               │
│   173 │                                                                                          │
│   174 │   for submodule in __collect_extra_submodules(DEBUG):                                    │
│ ❱ 175 │   │   if __load_extra_py_code_for_module("cv2", submodule, DEBUG):                       │
│   176 │   │   │   if DEBUG: print("Extra Python code for", submodule, "is loaded")               │
│   177 │                                                                                          │
│   178 │   if DEBUG: print('OpenCV loader: DONE')                                                 │
│                                                                                                  │
│ /usr/local/lib/python3.8/dist-packages/cv2/__init__.py:28 in __load_extra_py_code_for_module     │
│                                                                                                  │
│    25 │   export_module_name = "{}.{}".format(base, name)                                        │
│    26 │   native_module = sys.modules.pop(module_name, None)                                     │
│    27 │   try:                                                                                   │
│ ❱  28 │   │   py_module = importlib.import_module(module_name)                                   │
│    29 │   except ImportError as err:                                                             │
│    30 │   │   if enable_debug_print:                                                             │
│    31 │   │   │   print("Can't load Python code for module:", module_name,                       │
│                                                                                                  │
│ /usr/lib/python3.8/importlib/__init__.py:127 in import_module                                    │
│                                                                                                  │
│   124 │   │   │   if character != '.':                                                           │
│   125 │   │   │   │   break                                                                      │
│   126 │   │   │   level += 1                                                                     │
│ ❱ 127 │   return _bootstrap._gcd_import(name[level:], package, level)                            │
│   128                                                                                            │
│   129                                                                                            │
│   130 _RELOADING = {}                                                                            │
│                                                                                                  │
│ /usr/local/lib/python3.8/dist-packages/cv2/mat_wrapper/__init__.py:33 in <module>                │
│                                                                                                  │
│   30                                                                                             │
│   31 Mat.__module__ = cv.__name__                                                                │
│   32 cv.Mat = Mat                                                                                │
│ ❱ 33 cv._registerMatType(Mat)                                                                    │
│   34                                                                                             │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: partially initialized module 'cv2' has no attribute '_registerMatType' (most likely due to a 
circular import)

The above exception was the direct cause of the following exception:

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ in <module>:9                                                                                    │
│                                                                                                  │
│    6 from PIL import Image                                                                       │
│    7                                                                                             │
│    8 from diffusers import StableDiffusionPipeline                                               │
│ ❱  9 from optimum.intel import INCQuantizer, INCStableDiffusionPipeline                          │
│   10                                                                                             │
│   11 #todo: check                                                                                │
│   12 #parameter                                                                                  │
│ in _handle_fromlist:1039                                                                         │
│                                                                                                  │
│ /usr/local/lib/python3.8/dist-packages/transformers/utils/import_utils.py:1136 in __getattr__    │
│                                                                                                  │
│   1133 │   │   if name in self._modules:                                                         │
│   1134 │   │   │   value = self._get_module(name)                                                │
│   1135 │   │   elif name in self._class_to_module.keys():                                        │
│ ❱ 1136 │   │   │   module = self._get_module(self._class_to_module[name])                        │
│   1137 │   │   │   value = getattr(module, name)                                                 │
│   1138 │   │   else:                                                                             │
│   1139 │   │   │   raise AttributeError(f"module {self.__name__} has no attribute {name}")       │
│                                                                                                  │
│ /usr/local/lib/python3.8/dist-packages/transformers/utils/import_utils.py:1148 in _get_module    │
│                                                                                                  │
│   1145 │   │   try:                                                                              │
│   1146 │   │   │   return importlib.import_module("." + module_name, self.__name__)              │
│   1147 │   │   except Exception as e:                                                            │
│ ❱ 1148 │   │   │   raise RuntimeError(                                                           │
│   1149 │   │   │   │   f"Failed to import {self.__name__}.{module_name} because of the followin  │
│   1150 │   │   │   │   f" traceback):\n{e}"                                                      │
│   1151 │   │   │   ) from e                                                                      │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: Failed to import optimum.intel.neural_compressor because of the following error (look up to see its 
traceback):
partially initialized module 'cv2' has no attribute '_registerMatType' (most likely due to a circular import)

**Comment by echarlaix** [comment]
Hi @JiaojiaoYe1994, 

Your issue seems related to opencv, this might help : https://github.com/opencv/opencv-python/issues/591

**Comment by echarlaix** [comment]
Where you able to fix it on your side @JiaojiaoYe1994 ?

**Comment by JiaojiaoYe1994** [comment]
Yes, I have fixed that. thxs

Yours sincerely

Jiaojiao Ye,


Senior AI researcher

Zhejiang Lab

Institute of Intelligent Computing


Homepage: link <https://jiaojiaoye1994.github.io/jiaojiaoye/>

Tel: +86 15158339064
