### ISSUE TITLE
Documentation for OpenVINO missing half()

### ISSUE THREAD

**Issue by ngaloppo** [huggingface/optimum-intel#418]
The documentation for OpenVINO is missing information does not have any information about using half() to run models on GPU. The docs used to have this information, but it was removed.

Is this not required anymore? I.e. perhaps model.to("GPU") does this automatically? If so, how would one run on GPU with FP32 precision?

**Comment by echarlaix** [comment]
Hi @ngaloppo,

Since `openvino>=2023.0.0`, the format enabling the optimal performance will be default, `.half()` is thus no longer needed to enable FP16 on GPU
