### ISSUE TITLE
'OVStableDiffusionPipeline' object has no attribute 'image_processor'

### ISSUE THREAD

**Issue by IlyasMoutawwakil** [huggingface/optimum-intel#422]
Using main branches of `optimum` and `optimum-intel`.

A test started to fail in `optimum-benchmark`. I tested a minimal script and it also fails:

```python
from optimum.intel.openvino import OVStableDiffusionPipeline
model = "hf-internal-testing/tiny-stable-diffusion-torch" # or a runway model

pipe = OVStableDiffusionPipeline.from_pretrained(model, device="CPU", export=True)
pipe(prompt="prompt", num_inference_steps=1)
```

The error is `AttributeError: 'OVStableDiffusionPipeline' object has no attribute 'image_processor'`

The problem comes from the new `VaeImageProcessor` which was added in `optimum` but only for `ORTStableDiffusionPipelineBase`
`StableDiffusionPipelineMixin` that's used by `OVStableDiffusionPipeline` supposes its existence without instantiating it. 
Should it be added in each sub-package ?

**Comment by IlyasMoutawwakil** [comment]
I just noticed the PR #421, great work!

**Comment by echarlaix** [comment]
Yes we will merge https://github.com/huggingface/optimum-intel/pull/421 after the next `optimum` release !
