### ISSUE TITLE
Set a number of threads

### ISSUE THREAD

**Issue by wonkyoc** [huggingface/optimum-intel#446]
Related #269 

Minimum example
```python
from optimum.intel import OVStableDiffusionPipeline

model_id = "echarlaix/stable-diffusion-v1-5-openvino"
ov_config = {"INFERENCE_NUM_THREADS": 20}
pipeline = OVStableDiffusionPipeline.from_pretrained(model_id,
        ov_config=ov_config)
prompt = "sailing ship in storm by Rembrandt"
images = pipeline(prompt).images
```

`ov_config` does not work in this case. As a result, the system still uses 10 threads in total. Is this expected? or am I using a wrong parameter?

**Comment by echarlaix** [comment]
Hi @wonkyoc, thnaks for reporting this and apologies for the delay, do you still observe this issue with the latest openvino release ? 

cc @eaidova who might have some insight on this

**Comment by wonkyoc** [comment]
## Environment
```
$ optimum-cli env
- `optimum` version: 1.18.0.dev0
- `transformers` version: 4.38.2
- Platform: Linux-5.15.0-75-generic-x86_64-with-glibc2.35
- Python version: 3.10.9
- Huggingface_hub version: 0.21.4
- PyTorch version (GPU?): 1.13.1+cu117 (cuda availabe: True)
- Tensorflow version (GPU?): not installed (cuda availabe: NA)

$ pip list | grep openvino
openvino                      2024.0.0
openvino-telemetry            2023.2.1
```

Hi @echarlaix, thanks for getting back. I am still seeing this issue on the latest openvino. Please check the env. You can also check a piece of evidence via the below screenshot:
<img width="790" alt="image" src="https://github.com/huggingface/optimum-intel/assets/14952546/c7f4e45f-244b-4494-94d7-0d78472122e4">

**Comment by helena-intel** [comment]
@wonkyoc This is probably expected behaviour. If you set INFRENCE_NUM_THREADS to 2 I expect you will see that it is being respected. OpenVINO does not allocate more threads than the number of physical cores in the system. If your system supports hyperthreading, you can add {"ENABLE_HYPER_THREADING": True} to ov_config to use 20 threads. There are pros and cons about that and I recommend checking accuracy.

**Comment by wonkyoc** [comment]
This makes sense. The system uses hyperthreading. Thanks for your explanation! I am closing this issue.
