### ISSUE TITLE
 ModuleNotFoundError: No module named 'timm.layers'

### ISSUE THREAD

**Issue by eaidova** [huggingface/optimum-intel#449]
from optimum.intel.openvino.modeling_timm import TimmImageProcessor
optimum/intel/openvino/modeling_timm.py:9: in <module>
    from timm.layers.config import set_fused_attn
E   ModuleNotFoundError: No module named 'timm.layers'

issue can b e resolved with upgrading timm package (I have 0.4.12, very old) , looks like some lower bound required for timm dependency.

**Comment by echarlaix** [comment]
Thanks for reporting ! Will be fixed in : https://github.com/huggingface/optimum-intel/pull/461
