### ISSUE TITLE
Intel NNCF functions for Pruning, Distilling and Quantizing for Seq2Seq Task

### ISSUE THREAD

**Issue by SuperSecureHuman** [huggingface/optimum-intel#468]
Currently NNCF quantization dosent work for seq2seq via optimum. 

NNCF has some work on it, any ways to get it working with optimum?

https://github.com/intel/neural-compressor/tree/master/examples/pytorch/nlp/huggingface_models/summarization/quantization/ptq_dynamic/fx

https://github.com/intel/neural-compressor/tree/master/examples/pytorch/nlp/huggingface_models/translation

**Comment by echarlaix** [comment]
Hi @SuperSecureHuman and apologies for the late reply.

We currently support wright only quantization for seq2seq models, you can try it out with :

```python
model_id = "echarlaix/t5-small-openvino"
quantization_config = OVWeightQuantizationConfig(bits=8)
model = OVModelForSeq2SeqLM.from_pretrained(model_id, quantization_config=quantization_config)
```

We also plan to add more support for the quantization of activations in the future
