### ISSUE TITLE
Links to code in the documentation are broken

### ISSUE THREAD

**Issue by fxmarty** [huggingface/optimum-intel#48]
Similar issue to https://github.com/huggingface/optimum-habana/issues/100

See e.g. in https://huggingface.co/docs/optimum/main/en/intel_optimization , links to source (as https://github.com/huggingface/optimum.intel/blob/main/optimum/intel/neural_compressor/quantization.py#L341 ) use `optimum.intel` instead of `optimum-intel`, hence those links are broken.

**Comment by IlyasMoutawwakil** [comment]
this was fixed in https://github.com/huggingface/optimum-intel/pull/410
