### ISSUE TITLE
Safety checker is not working (OVStableDiffusionPipeline)

### ISSUE THREAD

**Issue by rupeshs** [huggingface/optimum-intel#505]
Safety checker is not working with OVStableDiffusionPipeline.

**Comment by rupeshs** [comment]
Hi @echarlaix , any update on this? 
Thanks.

**Comment by echarlaix** [comment]
Hi @rupeshs, this needs to be added to [`optimum.exporters`](https://huggingface.co/docs/optimum/main/en/exporters/onnx/usage_guides/contribute) and make sure it's compatible with [`StableDiffusionPipelineMixin`](https://github.com/huggingface/optimum/blob/cf82249b007da696c98b369e4857efe01267d640/optimum/pipelines/diffusers/pipeline_stable_diffusion.py#L403) and loaded in the pipeline https://github.com/huggingface/optimum-intel/blob/v1.15.2/optimum/intel/openvino/modeling_diffusion.py#L119, I don't have much bandwidth to do it in the coming weeks but if you have some time to work on the integration I'll be happy to help

**Comment by clinty** [comment]
@echarlaix could you advise on https://github.com/huggingface/optimum/pull/1783/ ?
