### ISSUE TITLE
Image inpainting is not working

### ISSUE THREAD

**Issue by rupeshs** [huggingface/optimum-intel#526]
Image inpainting is not working with OVStableDiffusionInpaintPipeline (LCM)
```python
from diffusers import LCMScheduler
from PIL import Image
from optimum.intel.openvino.modeling_diffusion import OVStableDiffusionInpaintPipeline


pipeline = OVStableDiffusionInpaintPipeline.from_pretrained(
    "rupeshs/LCM-dreamshaper-v7-openvino",
    local_files_only=False,
    ov_config={"CACHE_DIR": ""},
    device="cpu",
)
init_image = Image.open("init.png")
mask_image = Image.open("mask.png")
pipeline.scheduler = LCMScheduler.from_config(pipeline.scheduler.config)
result_images = pipeline(
    image=init_image,
    mask_image=mask_image,
    prompt="rayban glass",
    negative_prompt="",
    num_inference_steps=4,
    guidance_scale=1,
    num_images_per_prompt=1,
).images

result_images[0].save("result.png")

```
![image](https://github.com/huggingface/optimum-intel/assets/3255994/23c8020f-deef-4f90-980b-426b5ee295bb)

**Comment by echarlaix** [comment]
Hi @rupeshs, at the moment we only have support of Latent Consistency Models for the text-to-image task (see our [documentation](https://huggingface.co/docs/optimum/v1.17.1/en/intel/inference#latent-consistency-models)). To add its support, you'll need to add an `OVLatentConsistencyModelInpaintPipeline` class as done for Stable Diffusion https://github.com/huggingface/optimum-intel/blob/v1.15.2/optimum/intel/openvino/modeling_diffusion.py#L760
