### ISSUE TITLE
Image Classification Example is not working

### ISSUE THREAD

**Issue by NoushNabi** [huggingface/optimum-intel#574]
Image classification example under 
https://github.com/huggingface/optimum-intel/tree/main/examples/openvino/image-classification
is not working based on current requirement packages. 
It gives below error:
ValueError: Task image-classification is not compatible with this dataset! Available tasks: [], 
and had to downgrade to datasets==2.4.0.

**Comment by echarlaix** [comment]
Thanks for reporting this @NoushNabi, fixed in https://github.com/huggingface/optimum-intel/pull/598
