### ISSUE TITLE
incorrect documentation pipeline

### ISSUE THREAD

**Issue by rbrugaro** [huggingface/optimum-intel#742]
supported accelerators and pipeline tasks

**Comment by echarlaix** [comment]
Hi @rbrugaro, could you share a link to the incorrect documentation you're referring to, I'm not sure to get which section you're talking about (we don't have a section for the optimum-intel pipelines yet), don't hesitate to open a PR and tag me in if easier

**Comment by echarlaix** [comment]
Fixed in https://github.com/huggingface/optimum-intel/pull/743, thanks @rbrugaro !
