### ISSUE TITLE
[model enable] Request to enable gemma2 model exporting

### ISSUE THREAD

**Issue by peiqingj** [huggingface/optimum-intel#798]
Please support exporting the new model_type "gemma2".
[model card](https://huggingface.co/google/gemma-2-9b)
It has been supported in latest transformers. 
[reference](https://huggingface.co/docs/transformers/en/model_doc/gemma2)

**Comment by peiqingj** [comment]
<img width="1610" alt="image" src="https://github.com/huggingface/optimum-intel/assets/60091061/9bc1ba4b-536f-4d62-8acc-7124195a0d65">
gemma2 models are ranking high in [LMSYS Chatbot Arena Leaderboard](https://chat.lmsys.org/), especially considering its relatively small size.

**Comment by eaidova** [comment]
https://github.com/huggingface/optimum-intel/pull/876
