### ISSUE TITLE
OpenVINO EP doesn't work with ORTModelForSeq2SeqLM

### ISSUE THREAD

**Issue by prasad-pr-20** [huggingface/optimum-intel#932]
## Environment
OS: Windows
Optimum version: 1.22.0
optimum-intel: 1.19.0
openvino: 2024.4.0
Python version: 3.11.7 
onnx: 1.17.0

## Issue Description
Hi All,

I'm trying to run the M2M100 model with ORTModelForSeq2SeqLM using the model converted to onnx using optimum. When I try to change the provider to "OpenVINOExecutionProvider", I get the below error:

`EP Error C:\Users\user\Desktop\rel-1.19_final\onnxruntime\onnxruntime\core\session\provider_bridge_ort.cc:1637 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "C:\Users\user\Downloads\user_work_folder\optimum_work_folder\sample_venv\Lib\site-packages\onnxruntime\capi\onnxruntime_providers_openvino.dll"`

I see that the .dll file `onnxruntime_providers_openvino.dll` is present in the specified folder.  

To cross verify, I've also tested OpenVINO EP with the examples provided in the ONNX docs and they to work perfectly fine. 

Hence, It would be really helpful if anyone can comment if `OpenVINO EP is supported by OptimumORT`? And if yes, how do i enable the same.

Thanks in advance.

**Comment by echarlaix** [comment]
Hi @prasad-pr-20, we recommend to use instead `OVModelForSeq2SeqLM` directly to load your model, converting your model to the OpenVINO IR directly.

```python
from optimum.intel import OVModelForSeq2SeqLM

model_id = "google-t5/t5-small"
model = OVModelForSeq2SeqLM.from_pretrained(model_id)
```
you can find more info in our documentation : https://huggingface.co/docs/optimum/main/en/intel/openvino/inference
