### ISSUE TITLE
Why is inference_mode removed?

### ISSUE THREAD

**Issue by zsym-sjtu** [huggingface/optimum-intel#942]
https://github.com/huggingface/optimum-intel/pull/837#issue-2424489996

Is there any equivalent? Or should I use IPEXModelForxxx instead? Thanks!

**Comment by echarlaix** [comment]
Hi @zsym-sjtu, we recommend users to use the `IPEXModelForxxx` class to load their model or to use the optimum  pipelines directly :  

```python
from optimum.intel.pipelines import pipeline

pipe = ipex_pipeline("question-answering", model_id, accelerator="ipex")
output = pipe("He's a dreadful magician")
```

```python
