### ISSUE TITLE
Follow-up request after #916 due to issues on the OpenVINO side

### ISSUE THREAD

**Issue by andrei-kochin** [huggingface/optimum-intel#965]
T5 encoder is not working on a tiny model which prevents the model to be validated on a regular basis

https://github.com/huggingface/optimum-intel/pull/916#discussion_r1811266332

**Comment by andrei-kochin** [comment]
@IlyasMoutawwakil  please assign this on @eaidova

**Comment by eaidova** [comment]
blocked by https://github.com/openvinotoolkit/openvino/pull/27215

**Comment by eaidova** [comment]
fixed as part of https://github.com/huggingface/optimum-intel/pull/1016
